# Form implementation generated from reading ui file 'EquipmentManager_AddItem-AddExistingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Add_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 440)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Add_item_frame = QtWidgets.QFrame(parent=self.frame)
        self.Add_item_frame.setStyleSheet("#Add_item_frame {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(195, 25, 25);\n"
"border-radius: 30px;\n"
"}\n"
"   \n"
"\n"
"\n"
"\n"
"")
        self.Add_item_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Add_item_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Add_item_frame.setObjectName("Add_item_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Add_item_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Title_Frame_4 = QtWidgets.QFrame(parent=self.Add_item_frame)
        self.Title_Frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Title_Frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Title_Frame_4.setObjectName("Title_Frame_4")
        self.formLayout_16 = QtWidgets.QFormLayout(self.Title_Frame_4)
        self.formLayout_16.setObjectName("formLayout_16")
        self.Add_New_Item_Text_4 = QtWidgets.QLabel(parent=self.Title_Frame_4)
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Add_New_Item_Text_4.setFont(font)
        self.Add_New_Item_Text_4.setObjectName("Add_New_Item_Text_4")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Add_New_Item_Text_4)
        self.gridLayout_3.addWidget(self.Title_Frame_4, 0, 0, 1, 1)
        self.Name_Frame_4 = QtWidgets.QFrame(parent=self.Add_item_frame)
        self.Name_Frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Name_Frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Name_Frame_4.setObjectName("Name_Frame_4")
        self.formLayout_17 = QtWidgets.QFormLayout(self.Name_Frame_4)
        self.formLayout_17.setObjectName("formLayout_17")
        self.Name_text_4 = QtWidgets.QLabel(parent=self.Name_Frame_4)
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Name_text_4.setFont(font)
        self.Name_text_4.setObjectName("Name_text_4")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Name_text_4)
        self.comboBox = QtWidgets.QComboBox(parent=self.Name_Frame_4)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox)
        self.gridLayout_3.addWidget(self.Name_Frame_4, 1, 0, 1, 2)
        self.Quantity_frame_4 = QtWidgets.QFrame(parent=self.Add_item_frame)
        self.Quantity_frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Quantity_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Quantity_frame_4.setObjectName("Quantity_frame_4")
        self.formLayout_19 = QtWidgets.QFormLayout(self.Quantity_frame_4)
        self.formLayout_19.setObjectName("formLayout_19")
        self.Quantity_text_4 = QtWidgets.QLabel(parent=self.Quantity_frame_4)
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Quantity_text_4.setFont(font)
        self.Quantity_text_4.setObjectName("Quantity_text_4")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Quantity_text_4)
        self.Quantity_spinbox_4 = QtWidgets.QSpinBox(parent=self.Quantity_frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Quantity_spinbox_4.sizePolicy().hasHeightForWidth())
        self.Quantity_spinbox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(12)
        self.Quantity_spinbox_4.setFont(font)
        self.Quantity_spinbox_4.setObjectName("Quantity_spinbox_4")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Quantity_spinbox_4)
        self.gridLayout_3.addWidget(self.Quantity_frame_4, 2, 0, 1, 2)
        self.Category_frame_4 = QtWidgets.QFrame(parent=self.Add_item_frame)
        self.Category_frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Category_frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Category_frame_4.setObjectName("Category_frame_4")
        self.formLayout_20 = QtWidgets.QFormLayout(self.Category_frame_4)
        self.formLayout_20.setObjectName("formLayout_20")
        self.Category_text_4 = QtWidgets.QLabel(parent=self.Category_frame_4)
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Category_text_4.setFont(font)
        self.Category_text_4.setObjectName("Category_text_4")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Category_text_4)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.Category_frame_4)
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_2)
        self.gridLayout_3.addWidget(self.Category_frame_4, 3, 0, 1, 2)
        self.Cancel_button_newitem = QtWidgets.QPushButton(parent=self.Add_item_frame)
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel_button_newitem.setFont(font)
        self.Cancel_button_newitem.setStyleSheet("#Cancel_button_newitem {\n"
"    border: 2px solid #a80000;\n"
"    border-radius: 18px;\n"
"    padding: 8px 20px;\n"
"    min-width: 80px;\n"
"}\n"
"#Cancel_button_newitem {\n"
"    background-color: #ffffff;\n"
"    color: #a80000;\n"
"}\n"
"\n"
"#Cancel_button_newitem::hover{\n"
"    background-color:rgb(195, 25, 25);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.Cancel_button_newitem.setObjectName("Cancel_button_newitem")
        self.gridLayout_3.addWidget(self.Cancel_button_newitem, 4, 0, 1, 1)
        self.Add_item_button_newitem = QtWidgets.QPushButton(parent=self.Add_item_frame)
        font = QtGui.QFont()
        font.setFamily("Nunito ExtraBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Add_item_button_newitem.setFont(font)
        self.Add_item_button_newitem.setStyleSheet("#Add_item_button_newitem{\n"
"    border: 2px solid #a80000;\n"
"    border-radius: 18px;\n"
"    padding: 8px 20px;\n"
"    min-width: 80px;\n"
"}\n"
"#Add_item_button_newitem {\n"
"    background-color: #ffffff;\n"
"    color: #a80000;\n"
"}\n"
"\n"
"#Add_item_button_newitem::hover{\n"
"    background-color:rgb(195, 25, 25);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.Add_item_button_newitem.setObjectName("Add_item_button_newitem")
        self.gridLayout_3.addWidget(self.Add_item_button_newitem, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.Add_item_frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Add_New_Item_Text_4.setText(_translate("Dialog", "Add Item"))
        self.Name_text_4.setText(_translate("Dialog", "Name:"))
        self.comboBox.setItemText(0, _translate("Dialog", "Please Select"))
        self.Quantity_text_4.setText(_translate("Dialog", "Quantity: "))
        self.Category_text_4.setText(_translate("Dialog", "Category: "))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Please Select"))
        self.Cancel_button_newitem.setText(_translate("Dialog", "Cancel"))
        self.Add_item_button_newitem.setText(_translate("Dialog", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Add_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
