# Form implementation generated from reading ui file 'ProfessorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 323)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Professor_Frame = QtWidgets.QFrame(parent=Dialog)
        self.Professor_Frame.setStyleSheet("#Professor_Frame {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(195, 25, 25);\n"
"border-radius: 30px;\n"
"}")
        self.Professor_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Professor_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Professor_Frame.setObjectName("Professor_Frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Professor_Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lastName_box = QtWidgets.QLineEdit(parent=self.Professor_Frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lastName_box.setFont(font)
        self.lastName_box.setObjectName("lastName_box")
        self.gridLayout_2.addWidget(self.lastName_box, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ProfessorID_text = QtWidgets.QLabel(parent=self.Professor_Frame)
        self.ProfessorID_text.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ProfessorID_text.setFont(font)
        self.ProfessorID_text.setObjectName("ProfessorID_text")
        self.horizontalLayout_3.addWidget(self.ProfessorID_text)
        self.ProfessorID_box = QtWidgets.QLineEdit(parent=self.Professor_Frame)
        self.ProfessorID_box.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ProfessorID_box.setFont(font)
        self.ProfessorID_box.setObjectName("ProfessorID_box")
        self.horizontalLayout_3.addWidget(self.ProfessorID_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.Professor_title_text = QtWidgets.QLabel(parent=self.Professor_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Professor_title_text.sizePolicy().hasHeightForWidth())
        self.Professor_title_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Professor_title_text.setFont(font)
        self.Professor_title_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Professor_title_text.setObjectName("Professor_title_text")
        self.gridLayout_2.addWidget(self.Professor_title_text, 0, 0, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(parent=self.Professor_Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("#saveButton {\n"
"    border: 2px solid black;\n"
"    border-radius: 18px;\n"
"    padding: 8px 20px;\n"
"    min-width: 80px;\n"
"}\n"
"#saveButton {\n"
"    background-color: #ffffff;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#saveButton::hover{\n"
"    background-color:rgb(195, 25, 25);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=self.Professor_Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("#cancelButton {\n"
"    border: 2px solid black;\n"
"    border-radius: 18px;\n"
"    padding: 8px 20px;\n"
"    min-width: 80px;\n"
"}\n"
"#cancelButton {\n"
"    background-color: #ffffff;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#cancelButton::hover{\n"
"    background-color:rgb(195, 25, 25);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.gridLayout_2.addLayout(self.buttonLayout, 4, 0, 1, 1)
        self.firstName_box = QtWidgets.QLineEdit(parent=self.Professor_Frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.firstName_box.setFont(font)
        self.firstName_box.setObjectName("firstName_box")
        self.gridLayout_2.addWidget(self.firstName_box, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.Professor_Frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lastName_box.setPlaceholderText(_translate("Dialog", "Last Name"))
        self.ProfessorID_text.setText(_translate("Dialog", "ID Number:"))
        self.Professor_title_text.setText(_translate("Dialog", "PROFESSOR"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.firstName_box.setPlaceholderText(_translate("Dialog", "First Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
