# Form implementation generated from reading ui file 'StudentDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 331)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Student_Frame = QtWidgets.QFrame(parent=Dialog)
        self.Student_Frame.setStyleSheet("#Student_Frame {\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(195, 25, 25);\n"
"border-radius: 30px;\n"
"}")
        self.Student_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Student_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Student_Frame.setObjectName("Student_Frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Student_Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Student_title_text = QtWidgets.QLabel(parent=self.Student_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Student_title_text.sizePolicy().hasHeightForWidth())
        self.Student_title_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Student_title_text.setFont(font)
        self.Student_title_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Student_title_text.setObjectName("Student_title_text")
        self.gridLayout_2.addWidget(self.Student_title_text, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ID_text = QtWidgets.QLabel(parent=self.Student_Frame)
        self.ID_text.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ID_text.setFont(font)
        self.ID_text.setObjectName("ID_text")
        self.horizontalLayout_3.addWidget(self.ID_text)
        self.ID_box = QtWidgets.QLineEdit(parent=self.Student_Frame)
        self.ID_box.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ID_box.setFont(font)
        self.ID_box.setObjectName("ID_box")
        self.horizontalLayout_3.addWidget(self.ID_box)
        self.Yearlevel_text = QtWidgets.QLabel(parent=self.Student_Frame)
        self.Yearlevel_text.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Yearlevel_text.setFont(font)
        self.Yearlevel_text.setObjectName("Yearlevel_text")
        self.horizontalLayout_3.addWidget(self.Yearlevel_text)
        self.Yearlevel_Spinbox = QtWidgets.QSpinBox(parent=self.Student_Frame)
        self.Yearlevel_Spinbox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Yearlevel_Spinbox.setFont(font)
        self.Yearlevel_Spinbox.setMinimum(1)
        self.Yearlevel_Spinbox.setMaximum(5)
        self.Yearlevel_Spinbox.setObjectName("Yearlevel_Spinbox")
        self.horizontalLayout_3.addWidget(self.Yearlevel_Spinbox)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Program_text = QtWidgets.QLabel(parent=self.Student_Frame)
        self.Program_text.setMaximumSize(QtCore.QSize(78, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Program_text.setFont(font)
        self.Program_text.setObjectName("Program_text")
        self.horizontalLayout_2.addWidget(self.Program_text)
        self.programComboBox = QtWidgets.QComboBox(parent=self.Student_Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.programComboBox.setFont(font)
        self.programComboBox.setObjectName("programComboBox")
        self.programComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.programComboBox)
        self.genderComboBox = QtWidgets.QComboBox(parent=self.Student_Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genderComboBox.setFont(font)
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.genderComboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Professor_text = QtWidgets.QLabel(parent=self.Student_Frame)
        self.Professor_text.setMaximumSize(QtCore.QSize(77, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Professor_text.setFont(font)
        self.Professor_text.setObjectName("Professor_text")
        self.horizontalLayout.addWidget(self.Professor_text)
        self.comboBox = QtWidgets.QComboBox(parent=self.Student_Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.firstName_box = QtWidgets.QLineEdit(parent=self.Student_Frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.firstName_box.setFont(font)
        self.firstName_box.setObjectName("firstName_box")
        self.gridLayout_2.addWidget(self.firstName_box, 4, 0, 1, 1)
        self.lastName_box = QtWidgets.QLineEdit(parent=self.Student_Frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lastName_box.setFont(font)
        self.lastName_box.setObjectName("lastName_box")
        self.gridLayout_2.addWidget(self.lastName_box, 5, 0, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.saveButton = QtWidgets.QPushButton(parent=self.Student_Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("#saveButton {\n"
"    border: 2px solid black;\n"
"    border-radius: 18px;\n"
"    padding: 8px 20px;\n"
"    min-width: 80px;\n"
"}\n"
"#saveButton {\n"
"    background-color: #ffffff;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#saveButton::hover{\n"
"    background-color:rgb(195, 25, 25);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=self.Student_Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("#cancelButton {\n"
"    border: 2px solid black;\n"
"    border-radius: 18px;\n"
"    padding: 8px 20px;\n"
"    min-width: 80px;\n"
"}\n"
"#cancelButton {\n"
"    background-color: #ffffff;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#cancelButton::hover{\n"
"    background-color:rgb(195, 25, 25);\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.gridLayout_2.addLayout(self.buttonLayout, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.Student_Frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Student_title_text.setText(_translate("Dialog", "STUDENT"))
        self.ID_text.setText(_translate("Dialog", "ID Number:"))
        self.Yearlevel_text.setText(_translate("Dialog", "Year Level:"))
        self.Program_text.setText(_translate("Dialog", "Program:"))
        self.programComboBox.setItemText(0, _translate("Dialog", "Please Select"))
        self.genderComboBox.setItemText(0, _translate("Dialog", "Male"))
        self.genderComboBox.setItemText(1, _translate("Dialog", "Female"))
        self.genderComboBox.setItemText(2, _translate("Dialog", "Other"))
        self.Professor_text.setText(_translate("Dialog", "Professor: "))
        self.firstName_box.setPlaceholderText(_translate("Dialog", "First Name"))
        self.lastName_box.setPlaceholderText(_translate("Dialog", "Last Name"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
